---
- name: Setup cluster and BIGIP VMs
  hosts: localhost
  roles:
    - { role: bigip-ingress-setup }

- name: Setting BIGIP basic configuration
  hosts: [bigip]
  gather_facts: false
  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "{{ bigip_user }}"
    F5_PASSWORD: "{{ bigip_password }}"
    F5_VALIDATE_CERTS: "false"
    F5_SERVER_PORT: 443
  connection: local
  tasks:
    - name: Activate and Configure bigip VMs
      include_role:
        name: bigip-ingress-setup
        tasks_from: 50_bigip_activation.yml

- name: Set up CIS
  hosts: localhost
  tasks:
    - name: Setup BIGIP controller
      include_role:
        name: bigip-ingress-setup
        tasks_from: 60_bigip_ctrlr.yml