- name: disable SR-IOV Operator admission controller webhook on unsupported cards
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc patch sriovoperatorconfig default --type=merge -n openshift-sriov-network-operator --patch '{ "spec": { "enableOperatorWebhook": false } }'

- name: Generate SRIOV Network Node Policy yaml file
  template:
    src: sriov-network-node-policy.yaml.j2
    dest: "{{ bigip_tempdir.path }}/sriov-network-node-policy.yaml"

- name: Create SRIOV Network Node Policy
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc apply -f {{ bigip_tempdir.path }}/sriov-network-node-policy.yaml

- name: Wait for {{ bigip_worker_mcp }} MCP to start updating
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc wait --for=condition=Updating --timeout=300s mcp {{ bigip_worker_mcp }}
  register: mcp_updating
  changed_when: "'condition met' in mcp_updating.stdout"
  retries: 5
  delay: 60
  until: mcp_updating is success
  ignore_errors: true

- name: Wait for {{ bigip_worker_mcp }} MCP to be updated
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc wait --for=condition=Updated --timeout=1800s mcp {{ bigip_worker_mcp }}
  changed_when: false
  register: worker_lb_mcp_update
  retries: 10
  delay: 60
  until: not worker_lb_mcp_update.failed
  when: mcp_updating is changed

- name: Generate SRIOV Network yaml file
  template:
    src: sriov-network.yaml.j2
    dest: "{{ bigip_tempdir.path }}/sriov-network.yaml"

- name: Create SRIOV Networks 
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc apply -f {{ bigip_tempdir.path }}/sriov-network.yaml   