- name: Download RH-IT-ROOT-CA certificate 
  get_url:
    url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
    dest: "{{ bigip_tempdir.path }}/RH-IT-Root-CA.crt"

- name: Create registry certificate config map
  shell: |
    oc -n {{ bigip_namespace }} create configmap my-registry-certs --from-file {{ bigip_tempdir.path }}/RH-IT-Root-CA.crt

- name: Create Data volume
  k8s:
    state: present
    definition: "{{ lookup('template', 'datavolume.yaml.j2') }}"

- name: wait until datavolumes are imported
  environment:
    KUBECONFIG: "{{ bigip_kubeconfig }}"
  shell: |
    oc -n {{ bigip_namespace }} get dv/{{ item.key }}-volume -o json
  register: dv_status
  until: "(dv_status.stdout|from_json).status.phase == 'Succeeded'"
  retries: 60
  delay: 5
  loop: "{{ bigip_vms | dict2items }}"
